---
provides: [uvmf_ecc]
schema_version: 2.4.0
requires:
  - uvmf_lib
  - ecc_top
  - ecc_coverage
targets:
  tb:
    directories:
      - ${COMPILE_ROOT}/../rtl
      - ${COMPILE_ROOT}/../../libs/rtl
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/ECC_in_pkg
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/ECC_in_pkg/src
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/ECC_out_pkg
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/ECC_out_pkg/src
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/environment_packages/ECC_env_pkg
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/ECC/tb/parameters
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/ECC/tb/sequences
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/ECC/tb/tests
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/ECC/tb/testbench
    files:
#      - ${COMPILE_ROOT}/../rtl/ecc_reg_uvm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/ECC_in_pkg/ECC_in_pkg_hdl.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/ECC_in_pkg/ECC_in_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/ECC_in_pkg/src/ECC_in_driver_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/ECC_in_pkg/src/ECC_in_if.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/ECC_in_pkg/src/ECC_in_monitor_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/ECC_out_pkg/ECC_out_pkg_hdl.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/ECC_out_pkg/ECC_out_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/ECC_out_pkg/src/ECC_out_driver_bfm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/ECC_out_pkg/src/ECC_out_if.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/interface_packages/ECC_out_pkg/src/ECC_out_monitor_bfm.sv
#      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/environment_packages/ECC_env_pkg/registers/ECC_reg_model_top_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/environment_packages/ECC_env_pkg/ECC_env_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/ECC/tb/parameters/ECC_parameters_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/ECC/tb/sequences/ECC_sequences_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/ECC/tb/tests/ECC_tests_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/ECC/tb/testbench/hdl_top.sv
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/ECC/tb/testbench/hvl_top.sv
    tops:
      - hdl_top
      - hvl_top
  sim:
    pre_exec: 'echo "[PRE-EXEC] Copying ECC vector generator to $(pwd)" && cp $COMPILE_ROOT/../tb/ecdsa_secp384r1.exe .'
global:
  tool:
    vcs:
      default:
        - '-assert svaext'
        #- '-v2k_generate'
        #- '-timescale=1ns/1ps'
        - '-noinherit_timescale=1ns/1ps'
        #- '-ucli -i dump.ucli'
      #sim:
        #- '-ucli -i dump.ucli'
        # Suppress a warning due to calling $fgets as task instead of function
        # i.e. discarding the return value. This is in auto-generated code.
        - '+warn=noRVOSFD'
        # Suppress NOTE about repeated package imports within the same
        # package (each .svh file included in the auto-generated UVM _pkg.sv
        # files imports the same dependencies)
        - '-suppress=SV-LCM-PPWI'
      elab:
        # Suppress warnings about too few port connections - auto-generated interfaces
        # declare all signals as inout, but are driven at a lower layer than the
        # instantiation, so they will always flag this
        - '-suppress=TFIPC'
