---
provides: [hmac_ctrl]
schema_version: 2.4.0
requires:
  - libs
  - keyvault
  - sha512_masked_core
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/hmac_param_pkg.sv
      - $COMPILE_ROOT/rtl/hmac_reg_pkg.sv
      - $COMPILE_ROOT/rtl/hmac_ctrl.sv
      - $COMPILE_ROOT/rtl/hmac.sv
      - $COMPILE_ROOT/rtl/hmac_core.v
      - $COMPILE_ROOT/rtl/hmac_reg.sv
      - $COMPILE_ROOT/rtl/hmac_lfsr.sv
    tops: [hmac_ctrl]
  rtl_lint:
    directories: []
    waiver_files: 
      - $MSFT_REPO_ROOT/src/hmac/config/design_lint/hmac_ctrl/sglint_waivers
---
provides: [hmac_ctrl_tb]  
schema_version: 2.4.0
requires: 
  - hmac_ctrl
  - hmac_coverage
targets:
  tb:
    directories: 
      - $COMPILE_ROOT/tb
    files:
      - $COMPILE_ROOT/tb/hmac_ctrl_tb.sv
    tops: [hmac_ctrl_tb]
---
provides: [hmac_coverage]  
schema_version: 2.4.0
requires: 
  - hmac_ctrl
targets:
  tb:
    directories: 
      - $COMPILE_ROOT/coverage
    files:
      - $COMPILE_ROOT/coverage/hmac_ctrl_cov_if.sv
      - $COMPILE_ROOT/coverage/hmac_ctrl_cov_bind.sv
global:
  tool:
    vcs:
      default:
        - '-assert svaext'
        - +define+CLP_ASSERT_ON
        #- '-v2k_generate'
        #- '-timescale=1ns/1ps'
        - '-noinherit_timescale=1ns/1ps'
        #- '-ucli -i dump.ucli'
      #sim:
        #- '-ucli -i dump.ucli'
