provides: [kv_defines_pkg]
schema_version: 2.4.0
requires: []
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files: 
      - $COMPILE_ROOT/rtl/kv_defines_pkg.sv
      - $COMPILE_ROOT/rtl/kv_macros.svh
  tb:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/kv_defines_pkg.sv
      - $COMPILE_ROOT/rtl/kv_macros.svh
---
provides: [keyvault]
schema_version: 2.4.0
requires: 
  - libs
  - kv_defines_pkg
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/kv_reg_pkg.sv
      - $COMPILE_ROOT/rtl/kv_reg.sv
      - $COMPILE_ROOT/rtl/kv_defines_pkg.sv
      - $COMPILE_ROOT/rtl/kv.sv
      - $COMPILE_ROOT/rtl/kv_fsm.sv
      - $COMPILE_ROOT/rtl/kv_read_client.sv
      - $COMPILE_ROOT/rtl/kv_write_client.sv
    tops: [kv]
  rtl_lint:
    directories: []
    waiver_files:
      - $COMPILE_ROOT/config/design_lint/keyvault/sglint_waivers
    black_box:
      - kv_reg
global:
  tool:
    vcs:
      default:
        - '-assert svaext'
        #- '-v2k_generate'
