---
provides: [caliptra_tlul_pkg]
schema_version: 2.4.0
requires: 
  - edn_pkg
  - caliptra_prim_pkg
  - caliptra_prim_secded
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/caliptra_tlul_pkg.sv
      - $COMPILE_ROOT/rtl/caliptra_tlul_adapter_vh.sv
      - $COMPILE_ROOT/rtl/caliptra_tlul_adapter_reg.sv
      - $COMPILE_ROOT/rtl/caliptra_tlul_cmd_intg_gen.sv
      - $COMPILE_ROOT/rtl/caliptra_tlul_cmd_intg_chk.sv
      - $COMPILE_ROOT/rtl/caliptra_tlul_rsp_intg_gen.sv
      - $COMPILE_ROOT/rtl/caliptra_tlul_rsp_intg_chk.sv
      - $COMPILE_ROOT/rtl/caliptra_tlul_data_integ_dec.sv
      - $COMPILE_ROOT/rtl/caliptra_tlul_data_integ_enc.sv
      - $COMPILE_ROOT/rtl/caliptra_tlul_err.sv
      - $COMPILE_ROOT/rtl/caliptra_tlul_err_resp.sv
      - $COMPILE_ROOT/rtl/caliptra_tlul_fifo_sync.sv
      - $COMPILE_ROOT/rtl/caliptra_tlul_socket_1n.sv
      - $COMPILE_ROOT/rtl/caliptra_tlul_sram_byte.sv
      - $COMPILE_ROOT/rtl/caliptra_tlul_adapter_sram.sv
