# Copyright (C) Microsoft Corporation. All rights reserved.

# Go here for details on compile.yml syntax:
# https://dev.azure.com/ms-tsd/Ether/_git/sim-tools?path=%2FSourceFileSpec.docx&version=GBmaster

---
provides: [ecc_top]
schema_version: 2.4.0
requires:
  - libs
  - hmac_drbg
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/ecc_reg_pkg.sv
      - $COMPILE_ROOT/rtl/ecc_defines_pkg.sv
      - $COMPILE_ROOT/rtl/ecc_params_pkg.sv
      - $COMPILE_ROOT/rtl/ecc_dsa_uop_pkg.sv
      - $COMPILE_ROOT/rtl/ecc_pm_uop_pkg.sv
      - $COMPILE_ROOT/rtl/ecc_top.sv
      - $COMPILE_ROOT/rtl/ecc_reg.sv
      - $COMPILE_ROOT/rtl/ecc_dsa_ctrl.sv
      - $COMPILE_ROOT/rtl/ecc_dsa_sequencer.sv
      - $COMPILE_ROOT/rtl/ecc_scalar_blinding.sv
      - $COMPILE_ROOT/rtl/ecc_hmac_drbg_interface.sv
      - $COMPILE_ROOT/rtl/ecc_arith_unit.sv
      - $COMPILE_ROOT/rtl/ecc_pm_ctrl.sv
      - $COMPILE_ROOT/rtl/ecc_pm_sequencer.sv
      - $COMPILE_ROOT/rtl/ecc_ram_tdp_file.sv
      - $COMPILE_ROOT/rtl/ecc_fau.sv
      - $COMPILE_ROOT/rtl/ecc_montgomerymultiplier.sv
      - $COMPILE_ROOT/rtl/ecc_pe_first.sv
      - $COMPILE_ROOT/rtl/ecc_pe.sv
      - $COMPILE_ROOT/rtl/ecc_pe_final.sv
      - $COMPILE_ROOT/rtl/ecc_mult_dsp.sv
      - $COMPILE_ROOT/rtl/ecc_add_sub_mod_alter.sv
      - $COMPILE_ROOT/rtl/ecc_adder.sv
    tops: [ecc_top]
  rtl_lint:
    directories: []
    waiver_files:
      - $COMPILE_ROOT/config/design_lint/ecc_top/sglint_waivers
    black_box:
      - ecc_reg
---
provides: [ecc_top_tb]  
schema_version: 2.4.0
requires: 
  - ecc_top
  - keyvault
  - caliptra_top_defines
targets:
  tb:
    directories: 
      - $COMPILE_ROOT/tb
    files:
      - $COMPILE_ROOT/tb/ecc_top_tb.sv

    tops: [ecc_top_tb]
global:
  tool:
    vcs:
      default:
        - '-assert svaext'
        - +define+CLP_ASSERT_ON
        #- '-v2k_generate'
        #- '-timescale=1ns/1ps'
        - '-noinherit_timescale=1ns/1ps'
        #- '-ucli -i dump.ucli'
      #sim:
        #- '-ucli -i dump.ucli'
